### ISSUE TITLE
[1.18.2 forge] Crash, before any mod loaded

### ISSUE THREAD

**Issue by thelegitdolt** [CreativityShark/pyrotasticv2#1]
https://gist.github.com/thelegitdolt/691e0a10f87f789e7af67898f59f728c

don't think it's a mod incompat but yeah

**Comment by CreativityShark** [comment]
Yeah, it looks like I messed something up with the firework rocket model. I'll try to get a fix out ASAP.

**Comment by thelegitdolt** [comment]
thanks!

**Comment by CreativityShark** [comment]
Crash should be fixed with the newest version, should be approved soon.

**Comment by thelegitdolt** [comment]
has been fixed. thank you

**Comment by thelegitdolt** [comment]
this is really weird, i'm having this crash again

**Comment by thelegitdolt** [comment]
https://gist.github.com/thelegitdolt/a73de2511c42f0cb281f6578940d7c54 new crash report

**Comment by thelegitdolt** [comment]
i'm definitely using pyrostatic 2.0.3

**Comment by thelegitdolt** [comment]
is suddenly working now lol

**Comment by brisingraerowing** [comment]
I just ran into this on 1.19.2 with Pyrotastic 2.0.3.

**Comment by UrBoiTom** [comment]
I'm having the same problem

**Comment by CreativityShark** [comment]
This crash seems to be caused by another mod failing to load properly, and is out of my control. “latest.log” should tell which mod is causing problems.
![EEF173F4-4103-4249-BB80-D61A366A321C](https://user-images.githubusercontent.com/94210249/197645503-096328d6-93e3-469d-9733-0167ba4770c6.jpeg)
![AE691CF9-0DEC-411B-AA14-7CE7C8F094E7](https://user-images.githubusercontent.com/94210249/197645526-0d1d25c1-1f1d-401c-8763-ccf3dfc396e7.jpeg)
